#!/usr/bin/env bash
# ci_harness.sh - the binary-free part of the tests/decimal512 checks, for CI runners that cannot build ClickHouse.
#
# PRODUCTION BOUNDARY: runs no engine, no server and no container; no network, no credentials. It reads the repository
# and writes only a temporary directory.
#
# Checks (each prints PASS or FAIL; exit 1 if any fails, 0 otherwise):
#   1. the vendored tools are byte-identical to the recorded skill copies (tools/VENDORED.sha256)
#   2. the pinned matrix cases match their generators (tools/matrix/lock_cases.py --check)
#   3. the stateless references 10310-10316 are exactly what their independent oracle writes
#      (tools/gen_stateless_references.py)
#   4. every fail-closed rule of the gate fires on synthetic evidence (tools/gate_mutation_test.py)
#   5. every script parses (bash -n, python3 -m py_compile)
#   6. the registry and the selection are consistent: every selected stateless test exists with a reference, every
#      matrix selector and proof target of known_defects.json names a locked category, every open defect is matched
# What it does NOT do: run ClickHouse. Product correctness needs run_checks.sh --tier quick|full|release with a binary
# built from the same commit; a green harness says only that the checks themselves are intact.
set -u
HERE=$(cd "$(dirname "$0")" && pwd)
TREE=$(cd "$HERE/../.." && pwd)
T=$HERE/tools
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
FAILED=0
ok() { echo "PASS $1"; }
ko() { echo "FAIL $1"; [ -n "${2:-}" ] && echo "     $2"; FAILED=1; }
run() { local name=$1; shift; if "$@" > "$TMP/out" 2>&1; then ok "$name"; else ko "$name" "$(tail -5 "$TMP/out" | tr '\n' ' ' | cut -c1-400)"; fi; }

# 1. vendored copies
bad=0
while read -r h p _ sp; do
  case $h in '#'*|'') continue;; esac
  [ "$(sha256sum "$T/$p" 2>/dev/null | cut -d' ' -f1)" = "$h" ] || { echo "     $p differs from VENDORED.sha256 (skill $sp)"; bad=1; }
done < "$T/VENDORED.sha256"
[ $bad = 0 ] && ok "vendored tools match VENDORED.sha256" || ko "vendored tools match VENDORED.sha256"

# 2. case lock
run "matrix cases match the pinned lock (lock_cases.py --check)" python3 "$T/matrix/lock_cases.py" --check "$T/matrix/cases.lock.json"

# 3. stateless references from the independent oracle
mkdir -p "$TMP/refs"
if python3 "$T/gen_stateless_references.py" "$TMP/refs" > "$TMP/out" 2>&1; then
  diffs=$(for f in "$TMP"/refs/*; do cmp -s "$f" "$TREE/tests/queries/0_stateless/$(basename "$f")" || basename "$f"; done)
  n=$(ls "$TMP/refs" | wc -l)
  if [ -z "$diffs" ] && [ "$n" -gt 0 ]; then ok "stateless 10310-10316: $n files regenerated by the oracle, byte-identical"
  else ko "stateless references regenerated by the oracle" "differ: $diffs"; fi
else
  ko "stateless reference generator runs" "$(tail -3 "$TMP/out")"
fi

# 4. gate self-test on synthetic evidence
if python3 "$T/gate_mutation_test.py" "$T" > "$TMP/mut" 2>&1; then
  ok "check_gate.py: $(grep -c '^PASS' "$TMP/mut") counterexample/mutation checks pass"
else
  ko "check_gate.py counterexample/mutation checks" "$(grep -E '^(FAIL|     )' "$TMP/mut" | head -6 | tr '\n' ' ')"
fi

# 5. syntax
bad=0
for f in "$HERE"/*.sh "$T"/*.sh "$T"/compat/*.sh "$T"/replication/*.sh; do bash -n "$f" 2> "$TMP/out" || { echo "     $f: $(head -1 "$TMP/out")"; bad=1; }; done
for f in "$T"/*.py "$T"/matrix/*.py "$T"/perf/*.py; do python3 -m py_compile "$f" 2> "$TMP/out" || { echo "     $f: $(head -1 "$TMP/out")"; bad=1; }; done
[ $bad = 0 ] && ok "every script parses (bash -n, py_compile)" || ko "every script parses"

# 6. registry and selection consistency
if python3 - "$HERE" "$TREE" > "$TMP/out" 2>&1 <<'EOF'
import json, os, sys
here, tree = sys.argv[1], sys.argv[2]
lock = json.load(open(os.path.join(here, "tools/matrix/cases.lock.json")))["matrices"]
suite_matrix = {"midpoint-matrix": "midpoint", "midpoint-vector-matrix": "midpoint_vector", "ops-matrix": "ops", "keys-matrix": "keys"}
reg = json.load(open(os.path.join(here, "known_defects.json")))
problems = []
for d in reg["defects"]:
    for sel in d.get("match") or []:
        m = suite_matrix.get(sel.get("suite"))
        if m and sel.get("category") and not lock.get(m, {}).get("categories", {}).get(sel["category"]):
            problems.append(f"{d['id']}: selector category {sel['category']!r} has no locked cases in {m}")
    pr = d.get("proof")
    if pr:
        for c in pr.get("targets") or []:
            if not lock.get(pr.get("matrix"), {}).get("categories", {}).get(c):
                problems.append(f"{d['id']}: proof target {c!r} has no locked cases in {pr.get('matrix')}")
    if d.get("status") not in ("open", "fixed"):
        problems.append(f"{d['id']}: status {d.get('status')!r}")
    if d.get("status") == "fixed" and not d.get("fixed_by"):
        problems.append(f"{d['id']}: fixed without fixed_by")
    if "@SHA" in json.dumps(d):
        problems.append(f"{d['id']}: unresolved commit placeholder")
sel = []
for line in open(os.path.join(here, "stateless_tests.txt")):
    name = line.split("#", 1)[0].strip()
    if not name:
        continue
    sel.append(name)
    base = os.path.join(tree, "tests/queries/0_stateless", name)
    if not (os.path.exists(base + ".sql") or os.path.exists(base + ".sh")) or not os.path.exists(base + ".reference"):
        problems.append(f"selected test {name} has no .sql/.sh or no .reference")
    if "# exclude:" in line:
        kd = line.split("# exclude:", 1)[1].split(":", 1)[0].strip()
        if not any(x["id"] == kd and x.get("status") == "open" for x in reg["defects"]):
            problems.append(f"{name} is excluded for {kd}, which is not an open defect")
if len(sel) != len(set(sel)):
    problems.append("duplicate names in stateless_tests.txt")
for p in problems:
    print(p)
print(f"{len(reg['defects'])} registry entries ({sum(d.get('status') == 'open' for d in reg['defects'])} open), {len(sel)} selected tests")
sys.exit(1 if problems else 0)
EOF
then ok "registry and selection are consistent: $(tail -1 "$TMP/out")"
else ko "registry and selection are consistent" "$(head -5 "$TMP/out" | tr '\n' ' ')"; fi

echo "# ci_harness: $([ $FAILED = 0 ] && echo PASS || echo FAIL) (binary-free checks only; product checks need run_checks.sh with a build of this commit)"
exit $FAILED
